packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  "@biomejs/biome": true
  "@bundled-es-modules/glob": true
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  nx: true
  rolldown: true
  style-dictionary: true

autoInstallPeers: true
minimumReleaseAge: 10080 # 7 days

overrides:
  vite: "npm:rolldown-vite@7.3.1"
  esbuild: "^0.27.0"
  "@emnapi/core": "^1.7.1"
  "@emnapi/runtime": "^1.7.1"

peerDependencyRules:
  allowedVersions:
    react: "19"
    rollup: "4"
    vite: "6 || 7"

strictPeerDependencies: true
