import figma from '@figma/code-connect';

import { Alert } from '../src/Alert';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	Alert,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=8003%3A631',
	{
		props: {
			// These props were automatically mapped based on your linked code:
			isDismissable: figma.boolean('Dismissible'),
			status: figma.enum('State', {
				Neutral: 'neutral',
				Information: 'info',
				Warning: 'warning',
			}),
			variant: figma.enum('Variant', {
				Inline: 'inline',
			}),
			// No matching props could be found for these Figma properties:
			// "dismissible": figma.boolean('Dismissible'),
			// "actions": figma.boolean('Actions'),
			// "message": figma.string('Message'),
			// "header": figma.string('Header'),
			// "header": figma.boolean('Header?')
		},
		example: (props) => (
			<Alert isDismissable={props.isDismissable} status={props.status} variant={props.variant} />
		),
	},
);
