import figma from '@figma/code-connect';

import { BadgeIcon } from '../../icons/src/BadgeIcon';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	BadgeIcon,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A3636',
	{
		props: {
			// These props were automatically mapped based on your linked code:
			size: figma.enum('Size', {
				'16 (tiny)': 'tiny',
				'24 (small)': 'small',
				'36 (medium)': 'medium',
				'64 (large)': 'large',
			}),
			// No matching props could be found for these Figma properties:
			// "icon": figma.instance('icon'),
			// "color": figma.enum('Color', {
			//   "Gray": "gray",
			//   "Blue": "blue",
			//   "Cyan": "cyan",
			//   "Purple": "purple",
			//   "Pink": "pink",
			//   "Orange": "orange",
			//   "Yellow": "yellow",
			//   "Green": "green",
			//   "Gradient 1": "gradient-1",
			//   "Gradient 2": "gradient-2",
			//   "Gradient 3": "gradient-3",
			//   "Gradient 4": "gradient-4",
			//   "Gradient 5": "gradient-5",
			//   "Gradient 6": "gradient-6",
			//   "Gradient 7": "gradient-7"
			// })
		},
		example: (props) => <BadgeIcon size={props.size} />,
	},
);
