import figma from '@figma/code-connect';

import { Calendar } from '../src/Calendar';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	Calendar,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=10675%3A815',
	{
		props: {
			// No matching props could be found for these Figma properties:
			// "buttons": figma.boolean('Buttons?')
		},
		example: (props) => <Calendar {...props} />,
	},
);
