import figma from '@figma/code-connect';

import { CheckboxGroup } from '../src/CheckboxGroup';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	CheckboxGroup,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A33127',
	{
		props: {
			// These props were automatically mapped based on your linked code:
			name: figma.string('Validation message'),
			id: figma.string('Validation message'),
			// No matching props could be found for these Figma properties:
			// "description": figma.string('Description'),
			// "validationMessage": figma.string('Validation message'),
			// "description": figma.boolean('Description?'),
			// "hasLabel": figma.boolean('Has label?'),
			// "states": figma.enum('States', {
			//   "Default": "default",
			//   "Invalid": "invalid"
			// }),
			// "direction": figma.enum('Direction', {
			//   "Vertical": "vertical",
			//   "Horizontal": "horizontal"
			// })
		},
		example: (props) => <CheckboxGroup name={props.name} id={props.id} />,
	},
);
