import figma from '@figma/code-connect';

import { Checkbox } from '../src/Checkbox';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	Checkbox,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A32735',
	{
		props: {
			// These props were automatically mapped based on your linked code:
			isIndeterminate: figma.enum('Check', {
				Indeterminate: true,
			}),
			// No matching props could be found for these Figma properties:
			// "hasLabel": figma.boolean('Has label'),
			// "state": figma.enum('State', {
			//   "Base": "base",
			//   "Disabled": "disabled",
			//   "Invalid": "invalid"
			// }),
			// "focus": figma.boolean('Focus')
		},
		example: (props) => <Checkbox isIndeterminate={props.isIndeterminate} />,
	},
);
