import figma from '@figma/code-connect';

import { Collection } from '../src/Collection';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	Collection,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=4655%3A50682',
	{
		props: {
			// No matching props could be found for these Figma properties:
			// "contentType": figma.enum('Content type', {
			//   "Basic content": "basic-content",
			//   "Placeholder swap": "placeholder-swap",
			//   "Numeric": "numeric"
			// }),
			// "sort": figma.enum('Sort', {
			//   "None": "none",
			//   "Descending": "descending",
			//   "Ascending": "ascending"
			// }),
			// "2ndRow": figma.boolean('2nd row?')
		},
		example: (props) => <Collection {...props} />,
	},
);
