import figma from '@figma/code-connect';

import { DatePicker } from '../src/DatePicker';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	DatePicker,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=10833%3A38082',
	{
		props: {
			// No matching props could be found for these Figma properties:
			// "label": figma.boolean('Label?'),
			// "helpText": figma.boolean('Help text?'),
			// "helpText": figma.string('Help text'),
			// "state": figma.enum('State', {
			//   "Resting": "resting",
			//   ":hover": "-hover",
			//   ":focus-visible": "-focus-visible",
			//   ":active": "-active",
			//   "Invalid": "invalid",
			//   "Disabled": "disabled"
			// })
		},
		example: (props) => <DatePicker {...props} />,
	},
);
