import figma from '@figma/code-connect';

import { FieldGroup } from '../src/FieldGroup';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	FieldGroup,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A33319',
	{
		props: {
			// These props were automatically mapped based on your linked code:
			name: figma.string('Validation message'),
			// No matching props could be found for these Figma properties:
			// "legend": figma.boolean('Legend?'),
			// "legend": figma.string('Legend'),
			// "invalid": figma.boolean('Invalid?'),
			// "validationMessage": figma.string('Validation message'),
			// "customComponent": figma.instance('Custom component'),
			// "variant": figma.enum('Variant', {
			//   "Default": "default",
			//   "Custom": "custom"
			// })
		},
		example: (props) => <FieldGroup name={props.name} />,
	},
);
