import figma from '@figma/code-connect';

import { Link } from '../src/Link';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	Link,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A35013',
	{
		props: {
			// No matching props could be found for these Figma properties:
			// "link": figma.string('Link'),
			// "style": figma.enum('Style', {
			//   "Default": "default",
			//   "Subtle": "subtle"
			// }),
			// "state": figma.enum('State', {
			//   "Resting": "resting",
			//   "Visited": "visited",
			//   ":active": "-active",
			//   ":hover": "-hover",
			//   ":focus-visible": "-focus-visible"
			// }),
			// "size": figma.enum('Size', {
			//   "Body 1": "body-1",
			//   "Body 2": "body-2",
			//   "Small 1": "small-1"
			// }),
			// "fontWeight": figma.enum('Font weight', {
			//   "Regular": "regular",
			//   "Semibold": "semibold"
			// })
		},
		example: (props) => <Link {...props} />,
	},
);
