import figma from '@figma/code-connect';

import { Menu } from '../src/Menu';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	Menu,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A30701',
	{
		props: {
			// No matching props could be found for these Figma properties:
			// "slot1": figma.instance('Slot 1'),
			// "slot2": figma.instance('Slot 2'),
			// "slot3": figma.instance('Slot 3'),
			// "showSlot2": figma.boolean('Show slot 2?'),
			// "showSlot3": figma.boolean('Show slot 3?'),
			// "showSlot4": figma.boolean('Show slot 4?'),
			// "slot4": figma.instance('Slot 4')
		},
		example: (props) => <Menu {...props} />,
	},
);
