import figma from '@figma/code-connect';

import { Popover } from '../src/Popover';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	Popover,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=4431%3A2829',
	{
		props: {
			// No matching props could be found for these Figma properties:
			// "popoverContent": figma.instance('Popover content'),
			// "type": figma.enum('Type', {
			//   "Basic text": "basic-text",
			//   "Placeholder swap": "placeholder-swap"
			// })
		},
		example: (props) => <Popover {...props} />,
	},
);
