import figma from '@figma/code-connect';

import { ProgressBar } from '../src/ProgressBar';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	ProgressBar,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A37274',
	{
		props: {
			// These props were automatically mapped based on your linked code:
			size: figma.enum('Size', {
				Small: 'small',
				Medium: 'medium',
				Large: 'large',
			}),
			// No matching props could be found for these Figma properties:
			// "animation": figma.enum('Animation', {
			//   "Step 1": "step-1",
			//   "Step 2": "step-2",
			//   "Step 3": "step-3",
			//   "Step 4": "step-4"
			// })
		},
		example: (props) => <ProgressBar size={props.size} />,
	},
);
