import figma from '@figma/code-connect';

import { Radio } from '../src/Radio';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	Radio,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A33572',
	{
		props: {
			value: figma.string('Label'),
			checked: figma.boolean('Selected'),
			// No matching props could be found for these Figma properties:
			// "hasLabel": figma.boolean('Has label'),
			// "state": figma.enum('State', {
			//   "Base": "base",
			//   "Invalid": "invalid",
			//   "Disabled": "disabled"
			// }),
			// "selected": figma.boolean('Selected'),
			// "focus": figma.boolean('Focus')
		},
		example: (props) => <Radio {...props} />,
	},
);
