import figma from '@figma/code-connect';

import { SearchField } from '../src';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	SearchField,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=10993-56547',
	{
		props: {
			//hasLabel: figma.boolean('Has label'),
			//helpText: figma.string("Help text"),
		},
		example: (props) => <SearchField {...props} />,
	},
);
