import figma from '@figma/code-connect';
import { IconButton, Input } from '@launchpad-ui/components';
import { Icon } from '@launchpad-ui/icons';

import { Group } from '../src/Group';
import { Label } from '../src/Label';
import { SearchField } from '../src/SearchField';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	SearchField,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=10993%3A56547',
	{
		props: {
			label: figma.string('Label'),
			// No matching props could be found for these Figma properties:
			// "label": figma.boolean('Label?'),
			// "helpText": figma.boolean('Help text?'),
			// "state": figma.enum('State', {
			//   "Resting": "resting",
			//   ":hover": "-hover",
			//   ":focus-visible": "-focus-visible",
			//   ":active": "-active",
			//   "Invalid": "invalid",
			//   "Disabled": "disabled"
			// })
		},
		example: (props) => (
			<SearchField>
				<Label>Label</Label>
				<Group>
					<Icon name="search" size="small" />
					<Input placeholder="Enter a value" />
					<IconButton
						aria-label="clear"
						icon="cancel-circle-outline"
						size="small"
						variant="minimal"
					/>
				</Group>
				<Text slot="description">Description</Text>
			</SearchField>
		),
	},
);
