import figma from '@figma/code-connect';

import { Select } from '../src';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	Select,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=10974-97679',
	{
		props: {
			//label: figma.string('Label'),
			//helpText: figma.string('Help text'),
		},
		example: (props) => <Select {...props} />,
	},
);
