import figma from '@figma/code-connect';
import { Icon } from '@launchpad-ui/icons';

import { Button } from '../src/Button';
import { Label } from '../src/Label';
import { ListBox, ListBoxItem } from '../src/ListBox';
import { Popover } from '../src/Popover';
import { Select, SelectValue } from '../src/Select';
import { Text } from '../src/Text';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	Select,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=10974%3A97679',
	{
		props: {
			label: figma.string('Label'),
			description: figma.string('Description'),
			helpText: figma.string('Help text'),
			value: figma.string('Value'),
			// "state": figma.enum('State', {
			//   "Resting": "resting",
			//   ":hover": "-hover",
			//   ":focus-visible": "-focus-visible",
			//   ":active": "-active",
			//   "Invalid": "invalid",
			//   "Disabled": "disabled"
			// })
		},
		example: (props) => (
			<Select {...props}>
				{props.label && <Label>{props.label}</Label>}
				<Button>
					<SelectValue />
					<Icon name="chevron-down" size="small" />
				</Button>
				{props.description && <Text slot="description">{props.description}</Text>}
				<Popover>
					<ListBox>
						<ListBoxItem>Item one</ListBoxItem>
						<ListBoxItem>Item two</ListBoxItem>
						<ListBoxItem>Item three</ListBoxItem>
					</ListBox>
				</Popover>
				{props.helpText && <Text slot="description">{props.helpText}</Text>}
			</Select>
		),
	},
);
