import figma from '@figma/code-connect';

import { Switch } from '../src/Switch';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	Switch,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A34050',
	{
		props: {
			state: figma.enum('State', {
				Resting: 'resting',
				Hover: 'hover',
				Active: 'active',
				Focus: 'focus',
				Disabled: 'disabled',
			}),
			toggle: figma.boolean('Toggle'),
			// No matching props could be found for these Figma properties:
			// "toggle": figma.boolean('Toggle'),
			// "state": figma.enum('State', {
			//   "Resting": "resting",
			//   ":hover": "-hover",
			//   ":active": "-active",
			//   ":focus-visible": "-focus-visible",
			//   "Disabled": "disabled"
			// }),
			// "hasLabel": figma.enum('Has label', {
			//   "True": "true"
			// })
		},
		example: (props) => (
			<Switch isSelected={props.toggle} isDisabled={props.state === 'disabled'} />
		),
	},
);
