import figma from '@figma/code-connect';

import { Cell, Column, Row, Table, TableBody, TableHeader } from '../src/Table';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
	Table,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=4670%3A84987',
	{
		props: {
			// No matching props could be found for these Figma properties:
			// "rowState": figma.enum('Row state', {
			//   "Resting": "resting",
			//   ":hover": "-hover",
			//   ":focus-visible": "-focus-visible"
			// })
		},
		example: (props) => (
			<Table>
				<TableHeader>
					<Column>Column 1</Column>
					<Column>Column 2</Column>
					<Column>Column 3</Column>
				</TableHeader>
				<TableBody>
					<Row>
						<Cell>Cell 1</Cell>
						<Cell>Cell 2</Cell>
						<Cell>Cell 3</Cell>
					</Row>
				</TableBody>
			</Table>
		),
	},
);
