import figma from '@figma/code-connect';

import { Tab, TabList, TabPanel, Tabs } from '../src/Tabs';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	Tab,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1%3A45112',
	{
		props: {
			// These props were automatically mapped based on your linked code:
			rel: figma.string('Label'),
			selected: figma.boolean('Selected'),
			// No matching props could be found for these Figma properties:
			// "label": figma.string('Label'),
			// "selected": figma.boolean('Selected'),
			// "state": figma.enum('State', {
			//   "Resting": "resting",
			//   "Hover": "hover"
			// })
		},
		example: (props) => (
			<Tabs>
				<TabList aria-label="tabs">
					<Tab id="1">Tab 1</Tab>
					<Tab id="2">Tab 2</Tab>
					<Tab id="3">Tab 3</Tab>
				</TabList>
				<TabPanel id="1">Tab body 1</TabPanel>
				<TabPanel id="2">Tab body 2</TabPanel>
				<TabPanel id="3">Tab body 3</TabPanel>
			</Tabs>
		),
	},
);
