import figma from '@figma/code-connect';

import { Button } from '../src/Button';
import { ButtonGroup } from '../src/ButtonGroup';
import { Toast, ToastRegion, toastQueue } from '../src/Toast';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
	Toast,
	'https://www.figma.com/design/98HKKXL2dTle29ikJ3tzk7/%F0%9F%9A%80-LaunchPad?node-id=1-45160',
	{
		props: {
			/*variant: figma.enum('Variant', {
				Default: 'default',
				Snackbar: 'snackbar',
			}),*/
			// No matching props could be found for these Figma properties:
			// "message": figma.string('Message'),
			// "hasLink": figma.boolean('Has link'),
			// "link": figma.string('Link'),
			// "heading": figma.string('Heading'),
			// "dismissible": figma.boolean('Dismissible'),
			// "hasHeading": figma.boolean('Has heading'),
			// "state": figma.enum('State', {
			//   "Error": "error",
			//   "Info": "info",
			//   "Negative": "negative",
			//   "Neutral": "neutral",
			//   "Positive": "positive",
			//   "Success": "success"
			// })
		},
		example: (props) => (
			<div>
				<ToastRegion {...props} />
				<ButtonGroup>
					<Button onPress={() => toastQueue.add({ title: 'A success toast!', status: 'success' })}>
						Show toast
					</Button>
					<Button
						onPress={() => {
							for (const toast of toastQueue.visibleToasts) {
								toastQueue.close(toast.key);
							}
						}}
					>
						Clear
					</Button>
				</ButtonGroup>
			</div>
		),
	},
);
