name: Chromatic

on:
  push:
    branches:
      - '**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      storybookUrl: ${{ steps.chromatic.outputs.storybookUrl }}
    steps:
      - name: Get Token
        uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/production/common/launchpad-ui/chromatic-token = CHROMATIC_TOKEN'

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@07791f8243f4cb2698bf4d00426baf4b2d1cb7e0 # v13
        with:
          projectToken: ${{ env.CHROMATIC_TOKEN }}
          buildScriptName: 'storybook:build'
          exitOnceUploaded: true
          onlyChanged: true
          externals: packages/(icons/src/img|tokens/tokens)/**
