name: Figma Code Connect Publish

on:
  push:
    paths:
      - 'packages/components/figma/**'
      - 'packages/icons/figma/**'
    branches:
      - main

jobs:
  code-connect:
    name: Code Connect
    # Prevents action from publishing on forks
    if: github.repository == 'launchdarkly/launchpad-ui'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get Token
        uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/production/common/launchpad-ui/figma-access-token = FIGMA_ACCESS_TOKEN'

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Connect publish
        run: pnpm figma connect publish --exit-on-unreadable-files
