name: Sync tokens to Figma

on:
  push:
    paths:
      - 'packages/tokens/tokens/**'
      - 'packages/tokens/src/**'
    branches:
      - main

jobs:
  sync-tokens-to-figma:
    # Prevents action from publishing on forks
    if: github.repository == 'launchdarkly/launchpad-ui'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get Tokens
        uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: |
            /production/common/launchpad-ui/figma-file-key = FIGMA_FILE_KEY,
            /production/common/launchpad-ui/figma-token = FIGMA_TOKEN

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build tokens
        run: pnpm nx run @launchpad-ui/tokens:build

      - name: Sync tokens to Figma file
        run: pnpm nx run @launchpad-ui/tokens:sync
