name: Sync tokens to Figma

on:
  push:
    paths:
      - 'packages/tokens/tokens/**'
      - 'packages/tokens/src/**'
    branches:
      - main

jobs:
  sync-tokens-to-figma:
    # Prevents action from publishing on forks
    if: github.repository == 'launchdarkly/launchpad-ui'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: https://github.com/launchdarkly
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - uses: dkershner6/aws-ssm-getparameters-action@v2
        with:
          parameterPairs: |
            /production/common/launchpad-ui/figma-file-key = FIGMA_FILE_KEY,
            /production/common/launchpad-ui/figma-token = FIGMA_TOKEN
          withDecryption: 'true'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build tokens
        run: pnpm nx run @launchpad-ui/tokens:build

      - name: Sync tokens to Figma file
        run: pnpm nx run @launchpad-ui/tokens:sync
